//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.EngagementFabric.ResourceProviderWebService.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    internal partial class SubscriptionRegistration
    {
        public string SubscriptionId { get; set; }
        public string State { get; set; }
        public string TenantId { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string LocationPlacementId { get; set; }
        public string QuotaId { get; set; }
        public string RegisteredFeatures { get; set; }
    }
}
