//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.EngagementFabric.SmsProvider.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectorCredentialAssignmentEntity
    {
        public string EngagementAccount { get; set; }
        public string Provider { get; set; }
        public string Id { get; set; }
        public string ChannelType { get; set; }
        public bool Enabled { get; set; }
        public bool Active { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public string ExtendedCode { get; set; }
    }
}
