//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.EngagementFabric.SmsProvider.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectorAgentMetadataEntity
    {
        public string Provider { get; set; }
        public string Id { get; set; }
        public Nullable<System.DateTime> LastMessageSendTime { get; set; }
        public Nullable<System.DateTime> LastReportUpdateTime { get; set; }
        public Nullable<long> PendingReceive { get; set; }
        public System.DateTime Modified { get; set; }
    }
}
