//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.EngagementFabric.SocialProvider.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfoStorageAccount
    {
        public long StorageAccountId { get; set; }
        public string Name { get; set; }
        public string SubscriptionId { get; set; }
        public string ContainerType { get; set; }
        public string ConnectionString { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
    }
}
