//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.EngagementFabric.SocialProvider.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public string Account { get; set; }
        public string ChannelName { get; set; }
        public string ChannelId { get; set; }
        public byte[] ChannelProperties { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime ModifiedTime { get; set; }
    }
}
