//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.EngagementFabric.TenantCacheService.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotaEntity
    {
        public string AccountName { get; set; }
        public string QuotaName { get; set; }
        public int Remaining { get; set; }
        public int Quota { get; set; }
        public System.DateTime LastUpdatedTime { get; set; }
        public System.DateTime CreatedTime { get; set; }
    }
}
