//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.EngagementFabric.TenantCacheService.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantEntity
    {
        public string AccountName { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ResourceDescription { get; set; }
        public string SubscriptionId { get; set; }
        public string ResourceGroup { get; set; }
        public string Location { get; set; }
        public string SKU { get; set; }
        public string Tags { get; set; }
        public byte[] Timestamp { get; set; }
        public string ResourceId { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
    }
}
