// <copyright file="OutputResult.cs" company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.// Licensed under the MIT license.
// </copyright>

using System;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;

namespace Microsoft.Azure.EngagementFabric.DispatcherInterface.Contract
{
    /// <summary>
    /// Deliver response sent back to caller service
    /// </summary>
    [DataContract]
    public class OutputResult
    {
        public OutputResult()
        {
        }

        // DeliveryResponse will be null if message is dropped because of timeout in queue
        public OutputResult(OutputMessage message, DeliveryResponse response)
        {
            this.EngagementAccount = message.MessageInfo.EngagementAccount;
            this.MessageId = message.MessageInfo.MessageId;
            this.TrackingId = message.MessageInfo.TrackingId;
            this.ConnectorIdentifier = message.ConnectorCredential;

            this.BatchId = message.Id;
            this.Targets = message.Targets;
            this.Delivered = message.Delivered;
            this.DeliveryResponse = response;
        }

        // Input information from caller
        [DataMember]
        public string EngagementAccount { get; set; }

        [DataMember]
        public Guid MessageId { get; set; }

        [DataMember]
        public string TrackingId { get; set; }

        [DataMember]
        public ConnectorIdentifier ConnectorIdentifier { get; set; }

        // Output information generated by dispatcher service
        [DataMember]
        public Guid BatchId { get; set; }

        [DataMember]
        public ReadOnlyCollection<string> Targets { get; set; }

        [DataMember]
        public bool Delivered { get; set; }

        [DataMember]
        public DeliveryResponse DeliveryResponse { get; set; }
    }
}
