// <auto-generated>
// Copyright (c) Microsoft Corporation.// Licensed under the MIT license.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.EngagementFabric.AdminClient.Models
{

    /// <summary>
    /// Defines values for ResourceState.
    /// </summary>
    public static class ResourceState
    {
        public const string Active = "Active";
        public const string Pending = "Pending";
        public const string Forbidden = "Forbidden";
        public const string Disabled = "Disabled";
    }
}
