// <auto-generated>
// Copyright (c) Microsoft Corporation.// Licensed under the MIT license.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.EngagementFabric.AdminClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SmsAccountSettings
    {
        /// <summary>
        /// Initializes a new instance of the SmsAccountSettings class.
        /// </summary>
        public SmsAccountSettings()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SmsAccountSettings class.
        /// </summary>
        public SmsAccountSettings(bool promotionRestricted)
        {
            PromotionRestricted = promotionRestricted;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "promotionRestricted")]
        public bool PromotionRestricted { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
