// <auto-generated>
// Copyright (c) Microsoft Corporation.// Licensed under the MIT license.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.EngagementFabric.AdminClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Template
    {
        /// <summary>
        /// Initializes a new instance of the Template class.
        /// </summary>
        public Template()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Template class.
        /// </summary>
        /// <param name="tplType">Message type (Notification or Otp or
        /// Promotion). Possible values include: 'Notification', 'Otp',
        /// 'Promotion'</param>
        /// <param name="state">Possible values include: 'Active', 'Pending',
        /// 'Forbidden', 'Disabled'</param>
        public Template(string templateName = default(string), string signature = default(string), string tplType = default(string), string message = default(string), string state = default(string))
        {
            TemplateName = templateName;
            Signature = signature;
            TplType = tplType;
            Message = message;
            State = state;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "templateName")]
        public string TemplateName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "signature")]
        public string Signature { get; set; }

        /// <summary>
        /// Gets or sets message type (Notification or Otp or Promotion).
        /// Possible values include: 'Notification', 'Otp', 'Promotion'
        /// </summary>
        [JsonProperty(PropertyName = "tplType")]
        public string TplType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Active', 'Pending',
        /// 'Forbidden', 'Disabled'
        /// </summary>
        [JsonProperty(PropertyName = "state")]
        public string State { get; set; }

    }
}
