// <auto-generated>
// Copyright (c) Microsoft Corporation.// Licensed under the MIT license.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.EngagementFabric.AdminClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TemplateUpdateRequest
    {
        /// <summary>
        /// Initializes a new instance of the TemplateUpdateRequest class.
        /// </summary>
        public TemplateUpdateRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TemplateUpdateRequest class.
        /// </summary>
        /// <param name="state">Possible values include: 'Active', 'Pending',
        /// 'Forbidden', 'Disabled'</param>
        public TemplateUpdateRequest(string state, string stateMessage = default(string))
        {
            State = state;
            StateMessage = stateMessage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'Active', 'Pending',
        /// 'Forbidden', 'Disabled'
        /// </summary>
        [JsonProperty(PropertyName = "state")]
        public string State { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stateMessage")]
        public string StateMessage { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (State == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "State");
            }
        }
    }
}
