// <auto-generated>
// Copyright (c) Microsoft Corporation.// Licensed under the MIT license.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.EngagementFabric.AdminClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Tenant
    {
        /// <summary>
        /// Initializes a new instance of the Tenant class.
        /// </summary>
        public Tenant()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Tenant class.
        /// </summary>
        public Tenant(TenantTenantDescription tenantDescription = default(TenantTenantDescription))
        {
            TenantDescription = tenantDescription;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tenantDescription")]
        public TenantTenantDescription TenantDescription { get; set; }

    }
}
