// <auto-generated>
// Copyright (c) Microsoft Corporation.// Licensed under the MIT license.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.EngagementFabric.AdminClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TenantTenantDescription
    {
        /// <summary>
        /// Initializes a new instance of the TenantTenantDescription class.
        /// </summary>
        public TenantTenantDescription()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TenantTenantDescription class.
        /// </summary>
        public TenantTenantDescription(IList<AuthenticationRule> authenticationRules = default(IList<AuthenticationRule>))
        {
            AuthenticationRules = authenticationRules;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "authenticationRules")]
        public IList<AuthenticationRule> AuthenticationRules { get; set; }

    }
}
