//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.EngagementFabric.EmailProvider.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomainEntity
    {
        public string Domain { get; set; }
        public string EngagementAccount { get; set; }
        public string State { get; set; }
        public string Message { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
    }
}
