//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.EngagementFabric.EmailProvider.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmailServiceDbEntities : DbContext
    {
        public EmailServiceDbEntities()
            : base("name=EmailServiceDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConnectorCredentialAssignmentEntity> ConnectorCredentialAssignments { get; set; }
        public virtual DbSet<ConnectorCredentialEntity> ConnectorCredentials { get; set; }
        public virtual DbSet<ConnectorMetadataEntity> ConnectorMetadata { get; set; }
        public virtual DbSet<DomainEntity> Domains { get; set; }
        public virtual DbSet<EngagementAccountEntity> EngagementAccounts { get; set; }
        public virtual DbSet<GroupEntity> Groups { get; set; }
        public virtual DbSet<SenderAddressEntity> SenderAddresses { get; set; }
        public virtual DbSet<TemplateEntity> Templates { get; set; }
    }
}
